trigger: none

pool: my-agent-pool

resources:
  repositories:
    - repository: eks-setup-repo
      type: github
      endpoint: robot-shop
      name: akash66sheoran/eks-cluster-setup-terraform
    - repository: robot-shop-repo
      type: github
      endpoint: robot-shop
      name: akash66sheoran/robot-shop

jobs:
  - job: checkout_repos
    steps:
      - checkout: self
      - checkout: eks-setup-repo
      - checkout: robot-shop-repo

  - job: install_terraform
    dependsOn: checkout_repos
    steps:
      - bash: sudo apt update
      - bash: sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            wget -O- https://apt.releases.hashicorp.com/gpg | \
            gpg --dearmor | \
            sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            gpg --no-default-keyring \
            --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg \
            --fingerprint
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
            https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
            sudo tee /etc/apt/sources.list.d/hashicorp.list
      
      - bash: sudo apt update && sudo apt install terraform