trigger: none

pool: my-agent-pool

resources:
  repositories:
    - repository: eks-setup-repo
      type: github
      endpoint: robot-shop
      name: akash66sheoran/eks-cluster-setup-terraform
    - repository: robot-shop-repo
      type: github
      endpoint: robot-shop
      name: akash66sheoran/robot-shop

jobs:
  - job: checkout_repos
    steps:
      - checkout: self
        displayName: 'checkout self repo'
      - checkout: eks-setup-repo
        displayName: 'checkout eks-cluster-setup-terraform repo'
      - checkout: robot-shop-repo
        displayName: 'checkout robot-shop repo'
      
      - bash: ls $(Agent.BuildDirectory)/s
        displayName: 'list downloaded repos'
      
      - bash: echo '$(Agent.BuildDirectory)'
        displayName: 'Agent.BuildDirectory'
      
      - bash: echo '$(Build.SourcesDirectory)'
        displayName: 'Build.SourcesDirectory'

  # - job: install_terraform
  #   dependsOn: checkout_repos
  #   steps:
  #     - bash: sudo apt update
  #       displayName: 'update apt repository'

  #     - bash: sudo apt install -y gnupg software-properties-common
  #       displayName: 'install required dependencies'

  #     - task: Bash@3
  #       displayName: 'install hashicorp gpg key'
  #       inputs:
  #         targetType: 'inline'
  #         script: |
  #           wget -O- https://apt.releases.hashicorp.com/gpg | \
  #           gpg --dearmor | \
  #           sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null

  #     - task: Bash@3
  #       displayName: 'Verify the keys fingerprint'
  #       inputs:
  #         targetType: 'inline'
  #         script: |
  #           gpg --no-default-keyring \
  #           --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg \
  #           --fingerprint

  #     - task: Bash@3
  #       displayName: 'add the HashiCorp repository to apt sources list'
  #       inputs:
  #         targetType: 'inline'
  #         script: |
  #           echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
  #           https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
  #           sudo tee /etc/apt/sources.list.d/hashicorp.list
      
  #     - bash: sudo apt update && sudo apt install terraform -y
  #       displayName: 'update apt and install Terraform'

  # - job: setup_eks_cluster
  #   dependsOn: checkout_repos
  #   steps:
  #   - task: Bash@3
  #     displayName: 'terraform init'
  #     inputs:
  #       targetType: 'inline'
  #       script: 'terraform init'
  #       workingDirectory: '$(Agent.BuildDirectory)/s/eks-cluster-setup-terraform'
    
  #   - task: Bash@3
  #     displayName: 'terraform apply'
  #     env:
  #       AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
  #       AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
  #       AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
  #     inputs:
  #       targetType: 'inline'
  #       script: 'terraform apply --auto-approve'
  #       workingDirectory: '$(Agent.BuildDirectory)/s/eks-cluster-setup-terraform'
        