trigger: none

pool: my-agent-pool

resources:
  repositories:
    - repository: eks-setup-repo
      type: github
      endpoint: robot-shop
      name: akash66sheoran/eks-cluster-setup-terraform
    - repository: robot-shop-repo
      type: github
      endpoint: robot-shop
      name: akash66sheoran/robot-shop

steps:
- checkout: eks-setup-repo
- bash: ls $(Agent.BuildDirectory)/s