trigger: none

pool: my-agent-pool

resources:
  repositories:
    - repository: eks-setup-repo
      type: github
      endpoint: robot-shop
      name: akash66sheoran/eks-cluster-setup-terraform
    - repository: robot-shop-repo
      type: github
      endpoint: robot-shop
      name: akash66sheoran/robot-shop

jobs:
  - job: checkout_repos
    steps:
      - checkout: self
      - checkout: eks-setup-repo
      - checkout: robot-shop-repo

  - job: install_terraform
    dependsOn: checkout_repos
    steps:
      - bash: sudo apt update
      - bash: sudo apt install terraform -y
